# https://themes.gohugo.io/themes/tailbliss/
baseURL = "https://mediadrugs.com/"
title = "Mediadrugs"

languageCode = "en-us"
DefaultContentLanguage = "en"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
paginate = 9
darkmode_js = ["assets/js/darkmode.js"]
enableInlineShortcodes = true

[params]
author = ""
authorimage = "../assets/images/global/author.webp"
github = "https://github.com/mediadrugs"
facebook = "https://facebook.com/mediadrugs"
og_image = "/images/tailbliss-cover.png"
sitename = "Mediadrugs - Digital Marketing Agency"
twitter = "@mediadrugs"
description = "Mediadrugs is a media company that produces content for the web and other media. This is the website for Mediadrugs."

[params.analytics]
  [params.analytics.google]
    tagID = "GTM-525JVVPW"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Categories"
tag = "Tags"

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.104.0"
