name = "Mediadrugs"
license = "Apache-2.0"
licenselink = ""
description = "Mediadrugs is a media company that produces content for the web and other media. This is the website for Mediadrugs."

# The home page of the theme, where the source can be found.
homepage = "https://mediadrugs.com"

tags = ["media", "advertisement", "company", "social media", "productivity" ]
features = ["blog", "categories", "webp", "tailwind3", "alpinejs"]
